#ifndef GLAZINGSOLARFACTORVENTILATION_GLOBAL_H
#define GLAZINGSOLARFACTORVENTILATION_GLOBAL_H

#ifdef _WIN32
#if defined(GLAZINGSOLARFACTORVENTILATION_LIBRARY)
#  define GLAZINGSOLARFACTORVENTILATIONSHARED_EXPORT __declspec(dllexport)
#else
#  define GLAZINGSOLARFACTORVENTILATIONSHARED_EXPORT __declspec(dllimport)
#endif
#else
#  define GLAZINGSOLARFACTORVENTILATIONSHARED_EXPORT
#endif
#endif
