#ifndef CLIMATICCONDITIONWRAPPER_GLOBAL_H
#define CLIMATICCONDITIONWRAPPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLIMATICCONDITIONWRAPPER_LIBRARY)
#  define CLIMATICCONDITIONWRAPPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CLIMATICCONDITIONWRAPPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CLIMATICCONDITIONWRAPPER_GLOBAL_H
