#ifndef GLAZINGSOLARFACTOR_GLOBAL_H
#define GLAZINGSOLARFACTOR_GLOBAL_H

#ifdef _WIN32
#if defined(GLAZINGSOLARFACTOR_LIBRARY)
#  define GLAZINGSOLARFACTORSHARED_EXPORT __declspec(dllexport)
#else
#  define GLAZINGSOLARFACTORSHARED_EXPORT __declspec(dllimport)
#endif
#else
#  define GLAZINGSOLARFACTORSHARED_EXPORT
#endif
#endif // GLAZINGSOLARFACTOR_GLOBAL_H
