#ifndef GLAZINGUVALUEVENTILATION_GLOBAL_H
#define GLAZINGUVALUEVENTILATION_GLOBAL_H

#ifdef _WIN32
#if defined(GLAZINGUVALUEVENTILATION_LIBRARY)
#  define GLAZINGUVALUEVENTILATIONSHARED_EXPORT __declspec(dllexport)
#else
#  define GLAZINGUVALUEVENTILATIONSHARED_EXPORT __declspec(dllimport)
#endif
#else
#  define GLAZINGUVALUEVENTILATIONSHARED_EXPORT
#endif
#endif // GLAZINGUVALUEVENTILATION_GLOBAL_H


